name: Nageen Rishad
favicon: null
layout_spectrum: 0.6237085671164095
typography_spectrum: 0.6208861754275858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6402809440623969
  lightness: 0.3118952310178429
  saturation: 0.5465199698228389
  rhythmicContrast: 0.6392815676517785
purpose: []
